#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/parity"
command_args="${PARITY_OPTS:--d /var/lib/parity}"
command_user="${command_user:-parity:parity}"
command_background=yes
pidfile="/run/${RC_SVCNAME}.pid"
retry="${retry:-TERM/60/KILL/5}"
start_stop_daemon_args="${SSD_OPTS:-"-w 1000"}"

depend() {
	need net
}
