#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

: ${GCAT_USER:=onioncat}
: ${GCAT_PIDFILE:="/run/${SVCNAME}.pid"}

name="GaliCat"
command="/usr/bin/gcat"
command_args="-P ${GCAT_PIDFILE} ${GCAT_OPTS}"
command_user="${GCAT_USER}"
command_background=true
pidfile="${GCAT_PIDFILE}"

depend() {
	use net
	need i2p i2pd
}

start_pre() {
	checkpath -d -m 0750 -o ${GCAT_USER} "${GCAT_LOG%/*}"
}
