#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

name="OnionCat"
command="/usr/bin/ocat"
command_args="${OCAT_OPTS}"
command_user="${command_user:-onioncat:onioncat}"
command_background=yes
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
	use net
	need tor
}

start_pre() {
	checkpath -d -m 0750 -o "${command_user}" "${OCAT_LOGDIR}"
}
