#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

: ${OCAT_USER:=onioncat}
: ${OCAT_PIDFILE:="/run/${SVCNAME}.pid"}

name="OnionCat"
command="/usr/bin/ocat"
command_args="-P ${OCAT_PIDFILE} ${OCAT_OPTS}"
command_user="${OCAT_USER}"
command_background=true
pidfile="${OCAT_PIDFILE}"

depend() {
	use net
	need tor
}

start_pre() {
	checkpath -d -m 0750 -o ${OCAT_USER} "${OCAT_LOG%/*}"
}
