#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

output_log="${output_log:-/dev/null}"
error_log="${error_log:-/var/log/docker/error.log}"

pidfile="/run/${RC_SVCNAME}.pid"
command="/usr/bin/dockerd"
command_args="-p \"${pidfile}\" ${DOCKER_OPTS}"
retry="${retry:-TERM/30/KILL/5}"
start_stop_daemon_args="-b ${SSD_OPTS}
	-1 ${output_log} -2 ${error_log}"

rc_ulimit="${rc_ulimit:--n 1048576 -u unlimited}"
