#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

PGWEB_OPTS="${PGWEB_OPTS:---bind=127.0.0.1 --listen=8081}"

output_log="${output_log:-/dev/null}"
error_log="${error_log:-/var/log/pgweb/error.log}"

command="/usr/bin/pgweb"
command_args="${PGWEB_OPTS}"
command_user="${command_user:-pgweb:pgweb}"
command_background=yes
pidfile="/run/${RC_SVCNAME}.pid"
start_stop_daemon_args="${SSD_OPTS}
	-1 ${output_log} -2 ${error_log}"

depend() {
	need net
}
