#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

extra_started_commands="reload"
output_log="${output_log:-/dev/null}"
error_log="${error_log:-${RUNNER_LOGDIR}/error.log}"

name="${name:-GitLab Runner}"
command="/usr/bin/gitlab-runner"
command_args="run -c ${RUNNER_CONFIG} ${RUNNER_OPTS}"
command_background=yes
pidfile="/run/${RC_SVCNAME}.pid"
required_files="${RUNNER_CONFIG}"
retry="${retry:-TERM/30/KILL/5}"
start_stop_daemon_args="${SSD_OPTS}
	-1 ${output_log} -2 ${error_log}"

depend() {
	need localmount net
	after sshd
}

reload() {
	ebegin "Reloading ${name} configuration"
	start-stop-daemon --signal HUP --pidfile "${pidfile}"
	eend $? "Failed to reload ${name}"
}
